[package]
name = "OTE"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-bigint = "0.5.5"
crypto-primes = "0.5.0"
primitive-types = "0.13.1"
rand = "0.8.5"
rand_aes = "0.3.1"
rand_chacha = "0.3.1"
rayon = "1.10.0"
sha3 = "0.10.8"
